### ISSUE TITLE
Consistent Payment ID across payment lifecycle

### ISSUE THREAD

**Issue by ok300** [breez/breez-liquid-sdk#302]
A `Payment` is typically identified by `tx_id`.

However, for Receive Swaps, the `tx_id` can alternate between `lockup_tx_id` and `claim_tx_id`.

We should provide a consistent way to identify payments, from the moment they are included in `list_payments` as `Pending` until they are `Complete`.

**Comment by roeierez** [comment]
I don't think for receive swaps it is a good idea to change the tx id. In fact I think the payment_tx_data table should only contain wallet transactions.
