### ISSUE TITLE
Insufficient Funds error when calculating fee

### ISSUE THREAD

**Issue by dangeross** [breez/breez-liquid-sdk#333]
Using the `estimate_onchain_tx_fee()` can result in an Insufficient Funds error if calculating the refund tx fee. This is because it uses the onchain wallet to build the tx to calculate the fees while also checks if there is sufficient funds to send this amount.

**Comment by roeierez** [comment]
Good catch Ross, we should probably build the refund tx with some arbitrary fees only to get the weight and extract the real fees before actually broadcast it.
