### ISSUE TITLE
Allow option to only restore an existing wallet on `ConnectRequest`

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-liquid-sdk#350]
Add option to only restore an existing wallet on `connect`, otherwise return an error.

Respective Breez SDK PR: 
- https://github.com/breez/breez-sdk/pull/790

**Comment by dangeross** [comment]
But there is no node 🙂

**Comment by erdemyerebasmaz** [comment]
> But there is no node 🙂

Updated the title :)
