### ISSUE TITLE
Config's `zero_conf_min_fee_rate` floating point inaccuracy

### ISSUE THREAD

**Issue by dangeross** [breez/breez-liquid-sdk#371]
When requesting the `default_config` the `zero_conf_min_fee_rate` is return as:

testnet: 0.10000000149011612
mainnet: 0.009999999776482582

these should be:

testnet: 0.1
mainnet: 0.01

Maybe we should use msats to configure these values?

```
Config(liquid_electrum_url=blockstream.info:465, bitcoin_electrum_url=blockstream.info:993, working_dir=., network=LiquidNetwork.TESTNET, payment_timeout_sec=15, zero_conf_min_fee_rate=0.10000000149011612, zero_conf_max_amount_sat=None)

Config(liquid_electrum_url=blockstream.info:995, bitcoin_electrum_url=blockstream.info:700, working_dir=., network=LiquidNetwork.MAINNET, payment_timeout_sec=15, zero_conf_min_fee_rate=0.009999999776482582, zero_conf_max_amount_sat=None)
```

**Comment by ok300** [comment]
When I print the `Config`, I get feerates 0.1 and 0.01 respectively.

But I agree, saving them as `msat` avoids any rounding issues.

**Comment by dangeross** [comment]
> When I print the `Config`, I get feerates 0.1 and 0.01 respectively.

@ok300 could possibly be when passed through the uniffi bindings?

**Comment by ok300** [comment]
Agree, that can easily become an issue when converting floats to different languages and platforms.

`msat` is the way to go.
